GET http://localhost:5001/users

###
GET http://localhost:5001/users/6289dff99cddb525074faa5c

###
POST http://localhost:5001/users
Content-Type: application/json

{
    "name": "Bucataru Ioan",
    "email": "bucataruioan1@gmail.com",
    "gender" : "Male"
}

###
PATCH  http://localhost:5001/users/6289dff99cddb525074faa5c
Content-Type: application/json

{
    "name": "John",
    "email": "john@gmail.com",
    "gender" : "Male"
}

###
DELETE  http://localhost:5001/users/6289dff99cddb525074faa5c